### ISSUE TITLE
failed to build on ubuntu 12.04

### ISSUE THREAD

**Issue by garaemon** [mujin/controllerclientcpp#1]
``` sh
mkdir build
cd build
cmake .. && make
Linking CXX executable mujinexecutetask
cd /home/jskuser/ros/groovy/controllerclientcpp/build/samples && /usr/bin/cmake -E cmake_link_script CMakeFiles/mujinexecutetask.dir/link.txt --verbose=1
/usr/bin/c++       CMakeFiles/mujinexecutetask.dir/mujinexecutetask.cpp.o  -o mujinexecutetask -rdynamic ../src/libmujincontrollerclient.so.0.2.5 -lboost_thread-mt -lboost_date_time-mt -lcurl -Wl,-rpath,/home/jskuser/ros/groovy/controllerclientcpp/build/src: 
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::filesystem3::detail::directory_iterator_increment(boost::filesystem3::directory_iterator&, boost::system::error_code*)'
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::filesystem3::directory_entry::m_get_status(boost::system::error_code*) const'
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::filesystem3::detail::directory_iterator_construct(boost::filesystem3::directory_iterator&, boost::filesystem3::path const&, boost::system::error_code*)'
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::system::system_category()'
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::filesystem3::path_traits::convert(char const*, char const*, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::filesystem3::detail::dir_itr_close(void*&, void*&)'
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::filesystem3::path::filename() const'
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::filesystem3::path_traits::convert(wchar_t const*, wchar_t const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::system::generic_category()'
../src/libmujincontrollerclient.so.0.2.5: undefined reference to `boost::filesystem3::path::wchar_t_codecvt_facet()'
collect2: ld returned 1 exit status
make[2]: *** [samples/mujinexecutetask] Error 1
make[2]: Leaving directory `/home/jskuser/ros/groovy/controllerclientcpp/build'
make[1]: *** [samples/CMakeFiles/mujinexecutetask.dir/all] Error 2
make[1]: Leaving directory `/home/jskuser/ros/groovy/controllerclientcpp/build'
make: *** [all] Error 2

```

``` sh
 aptitude search boost | grep filesystem
i   libboost-filesystem-dev         - filesystem operations in C++ (default vers
p   libboost-filesystem-dev:i386    - filesystem operations in C++ (default vers
i   libboost-filesystem1.46-dev     - filesystem operations (portable paths, ite
p   libboost-filesystem1.46-dev:i38 - filesystem operations (portable paths, ite
i   libboost-filesystem1.46.1       - filesystem operations (portable paths, ite
p   libboost-filesystem1.46.1:i386  - filesystem operations (portable paths, ite
p   libboost-filesystem1.48-dev     - filesystem operations (portable paths, ite
p   libboost-filesystem1.48-dev:i38 - filesystem operations (portable paths, ite
p   libboost-filesystem1.48.0       - filesystem operations (portable paths, ite
p   libboost-filesystem1.48.0:i386  - filesystem operations (portable paths, ite
```
